export const trackLanguageOptions = [
  // Indian languages
  { code: 'hi', label: 'Hindi' },
  { code: 'ta', label: 'Tamil' },
  { code: 'te', label: 'Telugu' },
  { code: 'ml', label: 'Malayalam' },
  { code: 'kn', label: 'Kannada' },
  { code: 'bn', label: 'Bengali' },
  { code: 'pa', label: 'Punjabi' },
  { code: 'mr', label: 'Marathi' },
  { code: 'gu', label: 'Gujarati' },
  { code: 'or', label: 'Odia' },
  { code: 'as', label: 'Assamese' },
  { code: 'ur', label: 'Urdu' },
  { code: 'sa', label: 'Sanskrit' },
  { code: 'bho', label: 'Bhojpuri' },
  { code: 'raj', label: 'Rajasthani' },
  { code: 'har', label: 'Haryanvi' },
  { code: 'mai', label: 'Maithili' },
  { code: 'kok', label: 'Konkani' },
  { code: 'mni', label: 'Manipuri' },
  { code: 'ne', label: 'Nepali' },
  { code: 'si', label: 'Sinhala' },
  // International
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Spanish' },
  { code: 'fr', label: 'French' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'ar', label: 'Arabic' },
  { code: 'ko', label: 'Korean' },
  { code: 'ja', label: 'Japanese' },
  { code: 'zh', label: 'Mandarin' },
  { code: 'de', label: 'German' },
  { code: 'it', label: 'Italian' },
  { code: 'ru', label: 'Russian' },
  { code: 'tr', label: 'Turkish' },
  { code: 'sw', label: 'Swahili' },
];
